# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('shelter_id', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('from_shelter', models.IntegerField(null=True)),
                ('to_shelter', models.IntegerField(null=True)),
                ('departure_time', models.DateTimeField(null=True)),
                ('arrival_time', models.DateTimeField(null=True)),
                ('arrival_confirmed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(max_length=255, null=True)),
                ('hq_id', models.IntegerField(null=True)),
                ('need_water', models.BooleanField(default=True)),
                ('occupancy', models.IntegerField(null=True)),
                ('max_occupancy', models.IntegerField(null=True)),
                ('ready_to_accommodate', models.BooleanField(default=True)),
                ('power_status', models.BooleanField(default=True)),
                ('water_status', models.BooleanField(default=True)),
                ('connectivity_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('end_shelter', models.IntegerField(null=True)),
                ('last_shelter', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('able_bodied', models.BooleanField(default=True)),
                ('contact_number', models.IntegerField(null=True)),
            ],
        ),
    ]
