version: '2'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    ports:
    - 80:8080
    volumes:
    - ./src:/usr/src/app

  shell:
    build: .
    command: python manage.py shell
    ports:
    - 80:8080
    volumes:
    - ./src:/usr/src/app

  createsuperuser:
    build: .
    command: python manage.py createsuperuser
    ports:
    - 80:8080
    volumes:
    - ./src:/usr/src/app

  migrate:
    build: .
    command: python manage.py migrate
    ports:
    - 80:8080
    volumes:
    - ./src:/usr/src/app

  makemigrations:
    build: .
    command: python manage.py makemigrations
    ports:
    - 80:8080
    volumes:
    - ./src:/usr/src/app
